[[headers]]
  for = "/latest_news.json"
  [headers.values]
    cache-control = "no-cache, no-store, must-revalidate"
    Content-Type = "application/json"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
